name: Polaris Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  polaris:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - uses: bd-SrinathAkkem/repo-analyzer@v1
        with:
          repo_url: 'https://github.com/bd-SrinathAkkem/WebGoat'
          ai_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
