name: CI-Coverity-Basic
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
 
jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Coverity Scan
        uses: blackduck-inc/black-duck-security-scan@SIGINT-3638
        with:
          coverity_url: ${{ vars.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_project_name: ${{ github.event.repository.name }}
          coverity_stream_name: ${{ github.event.repository.name }}-${{ github.ref_name }}
          coverity_policy_view: 'Outstanding Issues'
 
          ### PULL REQUEST COMMENTS:
          #coverity_prComment_enabled: true
          #coverity_prComment_impacts: 'High'
          bridgecli_download_url: "https://artifactory.tools.duckutil.net/artifactory/clops-local/integrations/bridge/binaries/bridge-cli-bundle/latest/bridge-cli-bundle-macos_arm.zip"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mark_build_status: 'success'
 
      - name: Save Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bridge-logs
          path: ${{ github.workspace }}/.bridge
          include-hidden-files: true
